// GET ERRORS, CLEAR ERRORS GET PROFILE 
export const GET_ERRORS = 'GET_ERRORS';

// SET CURRENT USER
export const SET_CURRENT_USER = 'SET_CURRENT_USER';

// GET this PROFILE
export const GET_PROFILE = 'GET_PROFILE';

// PROFILE LOADING
export const PROFILE_LOADING = 'PROFILE_LOADING';

// PROFILE_NOT_FOUND
export const PROFILE_NOT_FOUND = 'PROFILE_NOT_FOUND';

// CLEAR_CURRENT_PROFILE - when you log out
export const CLEAR_CURRENT_PROFILE = 'CLEAR_CURRENT_PROFILE';

// GET All PROFILES
export const GET_PROFILES = 'GET_PROFILES';